version: "3.8"

services:
  backend:
    build: .
    container_name: jobboard-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017
      - DATABASE_NAME=jobboard
      - PORT=5000
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-change-in-production
      - JWT_EXPIRES_IN=1h
      - JWT_REFRESH_EXPIRES_IN=7d
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - FACEBOOK_APP_ID=your-facebook-app-id
      - FACEBOOK_APP_SECRET=your-facebook-app-secret
      - LINKEDIN_CLIENT_ID=your-linkedin-client-id
      - LINKEDIN_CLIENT_SECRET=your-linkedin-client-secret
      - APPLE_CLIENT_ID=your-apple-client-id
      - APPLE_TEAM_ID=your-apple-team-id
      - APPLE_KEY_ID=your-apple-key-id
      - APPLE_PRIVATE_KEY=your-apple-private-key
      - EMAIL_SERVICE=gmail
      - EMAIL_USER=your-email@gmail.com
      - EMAIL_PASS=your-email-password
      - FRONTEND_URL=http://localhost:5174
    depends_on:
      - mongo
    networks:
      - jobboard-network
    restart: unless-stopped
    volumes:
      - ./uploads:/app/backend/uploads
      - ./logs:/app/backend/logs

  mongo:
    image: mongo:7.0.0
    container_name: jobboard-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=jobboard
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - jobboard-network
    restart: unless-stopped

  # Optional: Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: jobboard-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - jobboard-network
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local

networks:
  jobboard-network:
    driver: bridge
